//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerococina2018.Library.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Configuracion
    {
        public int cve_configuracion { get; set; }
        public string descripcion { get; set; }
        public string contrasena { get; set; }
        public System.DateTime fecha_registro { get; set; }
    }
}
