//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Aerococina2018.Library.DL
{
    using System;
    using System.Collections.Generic;
    
    public partial class consumos
    {
        public int cve_consumo { get; set; }
        public int cve_producto { get; set; }
        public int cve_empleado { get; set; }
        public decimal precio { get; set; }
        public bool estatus { get; set; }
        public System.DateTime fecha_registro { get; set; }
    
        public virtual empleados empleados { get; set; }
        public virtual productos productos { get; set; }
    }
}
